### ISSUE TITLE
Issues with main.py

### ISSUE THREAD

**Issue by chadgoss** [Crystalnix/omaha-server#106]
1) This needs to be not hardcoded in main.py, need to be able to configure it.
  
  option_settings:
      'aws:autoscaling:launchconfiguration':
        InstanceType: t2.small

====================================
2) I believe option settings might need to have quotes
for example, REDIS_HOST: '10.6.0.11' instead of REDIS_HOST: 10.6.0.11 which is how main.py produces them in ebs.config.

===================================
3) the following needs to be added to settings.yml to avoid the error message "{"Error":{"Code":"ConfigurationValidationException","Message":"Configuration validation exception: Invalid option value: 'sg-bf57dad8' (Namespace: 'aws:autoscaling:launchconfiguration', OptionName: 'SecurityGroups'): The security group 'sg-bf57dad8' does not exist","Type":"Sender"},"RequestId":"436cef00-45f3-11e5-a0f5-01df443d11c0"}

Believe this has to be in the environment specific portion
      'aws:ec2:vpc':
            VPCId: xxxxxxxxxxxxxx
            Subnets: xxxxxxxxxx
            ELBSubnets: xxxxxxxxxxxxx
            DELETE THIS LINE>>>    ELBScheme: internal
            AssociatePublicIpAddress: true

===================================
4) we need to come up with a different strategy for security groups, currently we have pub, pri, common, but that will not work as each security group MUST be associated with a single VPC when it is created.

====================================
5) Although ebs.config says:
          'aws:autoscaling:launchconfiguration':
            'IamInstanceProfile': WIP-omahapriv
            'SecurityGroups': sg-bf57dad8

omahaserver-wip-priv gets created with two EC2 security groups:  sg-bf57dad8,sg-24d8be43
Is that expected?

**Comment by kyakovenko** [comment]
It seems this request is obsolete.
