### ISSUE TITLE
Fix download url in server response

### ISSUE THREAD

**Issue by namtb49** [Crystalnix/omaha-server#109]
In last post, I've asked for fix quick setup and deploy Crystalnix Server. Thanks for yurtaev for his favor and quick response. Now I can open Crystalnix Omaha server admin panel.

But when I upload new application in admin page, now that can't connect successful with my Omaha client. In details i see in update log, it assemble the reponse URL now change to relative url, not absolution url as before. In e.g, for now, it appeared that: "/static/media/test.exe" insteadof "http://ip:port/media/test.exe" as before. Because, some client app has fixture fully form of url, so now I must be remain those url at response.

I've try to tangled up with setting.py, admin.py but not give some result. Pls show me some clue to get formal content response

**Comment by yurtaev** [comment]
I added the environment variable `OMAHA_URL_PREFIX`. If you use the `DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'` you should set `OMAHA_URL_PREFIX=http://you-domain.com` (*no trailing slash*)

**Comment by namtb49** [comment]
Thanks for your advanced!
But I'm still geting stuck of tangled code chaos. Because in my prev try and probe with server side, I've build Crystalnix with not correctly setting, so when rebuld it again with paver, it's seem to be not change anything all. For eg, while i try modify settings.py as you describe in prev post, may be it's doesn't recomplie again to .pyc file, so all i see in the console is that some thing "redist_db has update", and when I debug the response, it doesn't anything change

Sorry for my ignorance, could you show  some command line ralate to force rebuild server to get effect for new setting file update ?

**Comment by yurtaev** [comment]
Try this:

```sh
$ docker-compose -f docker-compose.dev.yml -p dev stop
$ docker-compose -f docker-compose.dev.yml -p dev rm web
$ docker-compose -f docker-compose.dev.yml -p dev build web
$ paver up_local_dev_server
``

**Comment by namtb49** [comment]
Thanks for your patience at lately time ! 
At finish, with litle knowledge of python and Linux command, I try setup my server successful.
