### ISSUE TITLE
add build number as a searchable string for sentry

### ISSUE THREAD

**Issue by chadgoss** [Crystalnix/omaha-server#126]
We would like to be able to view in Sentry all crashes on build 'X' or greater for example.
thanks!

**Comment by anmekin** [comment]
Sentry doesn't support filtration like "greater than X". That means we can get all crashes on build X, but we can't get all crashes with build number greater than X.
I can suggest another way to filter crashes. We can do it on Omaha-Server. In this case, we will be able to get all crashes with build number greater than X, but they won't be aggregated like it's in Sentry.
