### ISSUE TITLE
Provide global delete button for all http log entries

### ISSUE THREAD

**Issue by chadgoss** [Crystalnix/omaha-server#127]
Instead of having to delete http log entries by individually opening and deleting, lets have a "select all" and a "delete" button functionality at the top level (delete button on the blue circle)

![image](https://cloud.githubusercontent.com/assets/9826215/11005455/eec7cc80-848b-11e5-8158-93680a0b1cb7.png)

**Comment by kyakovenko** [comment]
HttpLog has been removed from the production version.
