### ISSUE TITLE
Remove recording /healthcheck/status/ queries from httplog

### ISSUE THREAD

**Issue by chadgoss** [Crystalnix/omaha-server#129]
![image](https://cloud.githubusercontent.com/assets/9826215/11037645/bb7da802-86cc-11e5-8d00-38ffbe2e6819.png)

**Comment by anmekin** [comment]
I've just checked that healtcheck requests are not counted anymore. Unfortunately, we can't delete old healthcheck entries from your servers but I can say that they won't appear in the future. By the way, if these entries disturb you, you can delete them manually.

**Comment by chadgoss** [comment]
ok, thanks!
