### ISSUE TITLE
No statistics showing up after Sept 28 in one of our envs

### ISSUE THREAD

**Issue by chadgoss** [Crystalnix/omaha-server#130]
we have 3 different Omaha servers stood up, in one of them there are no sparrow statistics showing up after 28-Sept

![image](https://cloud.githubusercontent.com/assets/9826215/11037693/07eeff24-86cd-11e5-901d-a1a771b0652c.png)

**Comment by anmekin** [comment]
It's very strange behavior, something might block requests to our service or the browser might use a wrong URL to Omaha-server. Could you check what domain is used to check updates?

**Comment by kyakovenko** [comment]
In a private talk, we've figured out that the Omaha client sends all requests to a wrong server.
