### ISSUE TITLE
omaha crash cleanup not working properly?

### ISSUE THREAD

**Issue by chadgoss** [Crystalnix/omaha-server#132]
we have it set to “delete everything older than 60 days”, and “only store 1,000 duplicate crashes”, but we’re still seeing LARGE volumes of automated crash deletion where our file system utilization is under 10%.

![image](https://cloud.githubusercontent.com/assets/9826215/11037800/c1447bb6-86cd-11e5-8136-063f460a2ec2.png)
![image](https://cloud.githubusercontent.com/assets/9826215/11037857/09160a04-86ce-11e5-81d0-c471b3da9ed8.png)

**Comment by anmekin** [comment]
In general, all conditions like “delete everything older than 60 days” or  “only store 1,000 duplicate crashes” don't pay attention to a file system utilization. They are just triggered when they are true. So for 1000 duplicates, when repeated crashes are uploaded, Omaha-Server removes information about the oldest duplicates of these crashes.
Extended cleanup log entries should clarify this process. I've implemented the temporary solution when all necessary data about deleted crashes will be stored in Sentry. Currently, these changes are in the dev branch; tomorrow Egor's going to move them into the master branch, and you will be able to deploy them on your servers. 
I'll let you know when it's done.

**Comment by anmekin** [comment]
Hello Chad,
I’ve disabled auto deletion of crash duplicates. All changes are in the master branch and you can deploy them on servers. Currently, I’m working on improving Sentry log entries, they are almost done and I think we'll be able to try them on Monday. In the future, we’re going to use powerful logs in Splunk to prevent such situations.
