### ISSUE TITLE
Need an easy way to know how many users are on what version

### ISSUE THREAD

**Issue by chadgoss** [Crystalnix/omaha-server#135]
The current statistics page has bar charts that use colors, but it's extremely difficult to know how many users are actually on what version at the current time.

Could we add two simple tables:
Table 1:
![image](https://cloud.githubusercontent.com/assets/9826215/11661164/7afb110a-9d9e-11e5-8ead-80dd08bcb7c5.png)

Table 2: 
![image](https://cloud.githubusercontent.com/assets/9826215/11661299/3549885c-9d9f-11e5-85d2-0ae7241fde7a.png)

**Comment by kyakovenko** [comment]
Hello Chad,

Could you explain what kind of information table 2 should contain? As for me, it's very similar to information that is shown on the page with statistics for requests. 

And I would like to draw your attention that UserID isn't generated for MacOs users, if you need this information for MacOs, we should discuss it separately.

**Comment by kyakovenko** [comment]
It was done for Windows users.
