### ISSUE TITLE
Error when deploy Omaha server

### ISSUE THREAD

**Issue by namtb49** [Crystalnix/omaha-server#141]
Yesterdday, when I've synched with last update Omaha server source code to instatll in new dev server, it'couldn't be deploy correctly.
In more detail, in last stepI've successful run command: "paver up_local_dev_server" , 
it output in the console that all dev server, db has build succesful, and show that now i can signin to admin control panel with default user/ pass 

But when i  tried browser to this address {DOCKER_HOST}:9090/admin, (asssume that the env point to ip addpress of my dev server), nothing happen. 
I hve toedy to tangle and digged into some config and setting file of docker, omaha module but this is very hard to start when I don't have any certain solution

Please show me some clue to solve this problem

**Comment by namtb49** [comment]
One more problem. I've try to dump DOCKER_HOST to get correct value:
"echo $DOCKER_HOST"
but it's show nothing
so, I decided to explicit set DOCKER_HOST to my local_address by command:
docker export set DOCKER_HOST = "127.0.0.1", after that rebuild server success, but nothing happen when open it in web-browser

**Comment by yurtaev** [comment]
Could you show me the output from the following commands?

```shell
$ uname -a
$ docker info
$ docker-compose version
```

**Comment by namtb49** [comment]
This is my output from dev console:
$ uname -a
root@bchrome1:~# uname -a
Linux bchrome1 3.13.0-33-generic #58-Ubuntu SMP Tue Jul 29 16:45:05 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

root@bchrome1:~# docker info
Containers: 4
Images: 138
Storage Driver: devicemapper
 Pool Name: docker-253:1-131454-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file:
 Metadata file:
 Data Space Used: 2.763 GB
 Data Space Total: 107.4 GB
 Data Space Available: 104.6 GB
 Metadata Space Used: 6.005 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.141 GB
 Udev Sync Supported: false
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 3.13.0-33-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 4
Total Memory: 7.798 GiB
Name: bchrome1
ID: HKKX:XSV7:WHA5:BVJD:2GEA:PNOX:7Q3S:WOYQ:FYJZ:K7JB:IING:GQWB
WARNING: No swap limit support

And the last one, 
root@bchrome1:~/omaha-server# docker-compose --version
docker-compose version: 1.3.0
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013

Sorry for I don't know how to format code to clearly view.

**Comment by yurtaev** [comment]
Try upgrade docker & docker-compose

- https://docs.docker.com/engine/installation/ubuntulinux/
- https://docs.docker.com/compose/install/

**Comment by namtb49** [comment]
After upgrade to last version for both docker and docker compose, I can run last command, 
paver up_local_dev_server

It's showed that may be conflict in docker service docker-compose client and server.
There are error log:

docker-compose -f docker-compose.dev.yml -p dev up -d db
ERROR: client and server don't have same version (client : 1.19, server: 1.18)

Note that in prev try, I manually downgrade docker-compose to version 1.3.0 to build server successful, but it can't deploy in dev server as described in prev post

**Comment by namtb49** [comment]
Thanks for your patience. I decided make a fresh install in dev server and finally it working
But still one problem. In my dev machine I want to set $DOCKER_HOST variable point to some test address, but now when I rebuld server with paver, it raises error in docker-compose module such that:
 `
docker-compose -f docker-compose.dev.yml -p dev up -d db
Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.`

How can I setup or revert to this default env var. And if my dev server machine  has 2 ip address attach with it, how do I can set my server to listen from one candinate

**Comment by namtb49** [comment]
After take a fresh install with set port-forward config, I has solve my problem. Thanks for advance
