### ISSUE TITLE
Connection refused error

### ISSUE THREAD

**Issue by yukels** [Crystalnix/omaha-server#152]
I successfully checked out omaha-server repo and installed all required software (Docker, Raven, PIP etc) on my Mac 10.11 machine:

$ git clone https://github.com/Crystalnix/omaha-server.git
$ cd omaha-server

I create new docker machine
NAME     ACTIVE   DRIVER       STATE     URL             SWARM                   DOCKER   ERRORS
default         -        virtualbox   Running   tcp://192.168.99.100:2376                           v1.9.1   
omaha           *        virtualbox   Running   tcp://192.168.99.105:2376                           v1.9.1   

And run command:
$ paver up_local_dev_server

I see that container successfully up and run:
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                  NAMES
db30262c090d        dev_web             "paver docker_run"       22 hours ago        Up 22 hours         0.0.0.0:9090->80/tcp   dev_web_1
96debdd69fa3        redis:3             "/entrypoint.sh redis"   22 hours ago        Up 22 hours         6379/tcp               dev_redis_1
bd0c3cc0b386        postgres:9.4        "/docker-entrypoint.s"   22 hours ago        Up 22 hours         5432/tcp               dev_db_1 

But I got "connection refuse" error when I try to connect to the service ():
$ curl http://192.168.99.105:9090/admin/
curl: (7) Failed to connect to 192.168.99.105 port 9090: Connection refused

Please advice.

**Comment by yurtaev** [comment]
Can you try to open http://192.168.99.100:9090/admin/ ?

Could you show me the output from the following commands?

```sh
$ uname -a
$ echo $DOCKER_HOST
$ docker info
$ docker-compose version
```

Please, try to

**Comment by yukels** [comment]
**$ uname -a**
Darwin dyukelson-mac 15.0.0 Darwin Kernel Version 15.0.0: Wed Aug 26 16:57:32 PDT 2015; root:xnu-3247.1.106~1/RELEASE_X86_64 x86_64
**$ echo $DOCKER_HOST **
tcp://192.168.99.105:2376
**$ docker info**
Containers: 3
Images: 49
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 55
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.13-boot2docker
Operating System: Boot2Docker 1.9.1 (TCL 6.4.1); master : cef800b - Fri Nov 20 19:33:59 UTC 2015
CPUs: 1
Total Memory: 996.2 MiB
Name: omaha
ID: EAEY:BWHX:Z4WC:GJJK:JIEX:WM6S:JES6:ZJE7:YDXA:Z4RW:XJFQ:PDJK
Debug mode (server): true
 File Descriptors: 27
 Goroutines: 47
 System Time: 2016-01-28T15:15:13.782059154Z
 EventsListeners: 0
 Init SHA1: 
 Init Path: /usr/local/bin/docker
 Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
**$ docker-compose version**
docker-compose version 1.5.2, build 7240ff3
docker-py version: 1.5.0
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1j 15 Oct 2014
 
And I got the same results for 192.168.99.100
**$ curl http://192.168.99.100:9090/admin/**
curl: (7) Failed to connect to 192.168.99.100 port 9090: Connection refused

**Comment by yurtaev** [comment]
Can you show output for:

```sh
$ docker-compose -f docker-compose.dev.yml -p dev ps
$ docker-compose -f docker-compose.dev.yml -p dev logs web
```

**Comment by yukels** [comment]
I pull your fix and now I able to connect to the server!
Thanks a lot!
