### ISSUE TITLE
'noupdate' response when response should contain update info

### ISSUE THREAD

**Issue by FrankPerryCarbonite** [Crystalnix/omaha-server#161]
I have followed the instructions on the wiki for deploying the omaha-server to Elastic Beanstalk, but I'm getting a noupdate response even though I believe I am sending a valid request. I have setup my app and versions as follows:

![Image of Application](https://cloud.githubusercontent.com/assets/7770112/13336058/1cb8f7a6-dbe2-11e5-9a8b-29257e5333db.png)

![Image of Channel](https://cloud.githubusercontent.com/assets/7770112/13336110/66ffe20c-dbe2-11e5-98e2-8ea83dae843a.png)

![Image of Platforms](https://cloud.githubusercontent.com/assets/7770112/13336125/7c89aefa-dbe2-11e5-9c9f-55a1daeba885.png)

![Image of Versions](https://cloud.githubusercontent.com/assets/7770112/13336146/926af454-dbe2-11e5-87c7-dce7672204b4.png)

Here is the request that I am sending to the server:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<request protocol="3.0" version="omahatest-1.0.0.0" ismachine="0" requestid="{2A0C621D-4B4A-410C-B101-4DD047EE7F27}" sessionid="{3B9B6B57-5AC7-446D-BC5f-5ED4E90350DB}" installsource="restclient">
  <os platform="win" version="8" sp="" arch="x64"></os>
  <app appid="{E96281A6-D1AF-4BDE-9A0A-97B76E56DC57}" version="0.0.0.0" nextversion="" lang="" brand="" client="" tag="stable">
   <updatecheck></updatecheck>
 </app>
</request>
```

And here is the response that I am receiving back:

```xml
<?xml version='1.0' encoding='UTF-8' ?>
 <response protocol="3.0" server="prod">
  <daystart elapsed_seconds="78897" />
  <app status="ok" appid="{E96281A6-D1AF-4BDE-9A0A-97B76E56DC57}">
   <updatecheck status="noupdate" />
  </app>
 </response>
```

I **think** I have configured everything correctly and am sending XML that should produce an update response. Is there something in anything above that jumps out as obviously wrong?

**Comment by shashkin** [comment]
Hi @FrankPerryCarbonite ,
In server admin, please, try to put your application id into braces so it look like `{E96281A6-D1AF-4BDE-9A0A-97B76E56DC57}` (note `{` and `}`).
This should help.

**Comment by FrankPerryCarbonite** [comment]
Hey @shashkin 
Thanks for your fast response. I did as you explained:

![Image of New Applications](https://cloud.githubusercontent.com/assets/7770112/13342620/83205ca8-dc11-11e5-88b3-005baa2e3021.png)

However, I submit the same exact updatecheck request posted above and get mostly the same response (elapsed_seconds is different, but I'd expect that almost to never be consistent).

**Comment by FrankPerryCarbonite** [comment]
Hey @shashkin 

I updated the app as you explained and modified the version as necessary and now am receiving the response I expect to get. Thanks for the clarification!
