### ISSUE TITLE
Code red

### ISSUE THREAD

**Issue by xDrFred** [Crystalnix/omaha-server#198]
Hey guys

I'm currently investigating the code red feature and can't find any documentation.
Furthermore I found no endpoint in the server on "/service/check2" which is the default location where the crashes are sent to.

Are there any sources out there?
Does crystalnix/omaha-server eaven support this feature?

Thanks for your help.

**Comment by kyakovenko** [comment]
Hello xDrFred,

At the moment, Omaha-server doesn't support this feature.

**Comment by xDrFred** [comment]
Thanks for the info.
Are there any intentions of implementing this?

**Comment by kyakovenko** [comment]
Hi xDrFred,

Yes, there are. We want to make a rollback somehow and red code looks as an 	
proper way for this but the task is in our backlog list and its priority is the lowest. However, I hope it'll be implemented to the end of this year.

**Comment by xDrFred** [comment]
Thanks for the info. I'll keep on observing this one
