### ISSUE TITLE
Determining software update channel, 'tag' value vs 'ap' value.

### ISSUE THREAD

**Issue by evgsid** [Crystalnix/omaha-server#200]
Hi guys,
omaha documentation mentioned that `tag` value should be used for determining update channels.
But real life is harsh, and in the last omaha sources (at least from 1.3.29.5)  google remove `tag` field at all from sources, and use `ap` field instead.
Are you interesting in supporting this new way, maybe together with `tag` field?

**Comment by kyakovenko** [comment]
Hello Evgeny,

Yes, we are. At the moment, we're using a lesser version of the Omaha client than you. We have plans to update it and update Omaha protocol at the server side. But it's not urgent for us, so I can't say when we're going to do it.

If you can implement such support, you are welcome. Just send your PL to the dev branch.

**Comment by anmekin** [comment]
Hello Evgeny,

We've added support for `ap` field. Now you can use both fields.
