### ISSUE TITLE
automatic upload of installers to omaha server

### ISSUE THREAD

**Issue by yukels** [Crystalnix/omaha-server#202]
Hey guys

We are interested in integration our automatic build system (based on Jenkins) with omaha server. We would like to upload to the server successfully created installers. 
How can I pass thru http request all needed information: application, version, channel, actions, user credentials  and file itself? Could you guide me, please?

**Comment by kyakovenko** [comment]
Hello yukels,

Omaha server has REST API which allows to manage all data that you need. You can find descriptions and examples of APIs by this link: http://crystalnix.github.io/omaha-server

**Comment by yukels** [comment]
Hi Kirill
Very useful link! I had some problems with the last slash in url and to download installer file. But after simple google search I found the right way to add a new version to the omaha server using the curl client.
It will be nice if you can improve your documentation:
- Add the slash to the end of sample urls. 
- Prepare a sample of curl request to add a new version with file to upload.

It will simplify integration for other developers used your open source.

Thanks a lot!

**Comment by anmekin** [comment]
Hi yukels,

We've updated API documentation. Now sample urls contain the slash at the end.
