### ISSUE TITLE
BUG: Adding a crash report results in an exception

### ISSUE THREAD

**Issue by xDrFred** [Crystalnix/omaha-server#203]
Hey guys

When I try to add a crash report with the ui I get an exception.

AttributeError at /admin/crash/crash/add/
'NoneType' object has no attribute 'name'
Request Method:	POST
Request URL:	http://devomaha/admin/crash/crash/add/
Django Version:	1.8.6
Exception Type:	AttributeError
Exception Value:	
'NoneType' object has no attribute 'name'
Exception Location:	./crash/forms.py in clean_upload_file_minidump, line 55
Python Executable:	/usr/local/bin/uwsgi
Python Version:	2.7.6

This is how I can reproduce the problem.
Login as admin to the web ui and browse to "crash reports" -> "crashes".
Click add crash. Click save.

**Comment by kyakovenko** [comment]
Hello xDrFred,

Thank you for the report, we'll check and fix it.

**Comment by xDrFred** [comment]
I still get an exception when I try to save an empty crash but it's working now when a dmp File is uploaded. Furthermore when I try to upload a crash report which would exeed the file system size I get an exception. (Maybe display a message in the ui?)

**Comment by xDrFred** [comment]
More about the crash feature:
- When I add a crash description and try to link it directly to an crash the displayed list shows items with the text "crash object". => /display something more usefull)
- When I try to add a pdb symbol file to the symbols "The file contains invalid data" gets displayed as soon as I click save

**Comment by xDrFred** [comment]
ok fatal error....

When I upload a crash with the field "stacktrace_json" I have some problems...
Uploading or/and adding itself works fine.. but when I try to view the crashes on my system I get an exception.
![image](https://cloud.githubusercontent.com/assets/20086318/17100365/36400b12-526e-11e6-90b3-e1c6464bfddb.png)
I can't navigate to the crash site until the crash with the "stacktrace_json" gets deleted.
As adding a crash can be done without login this is eaven more essential.

**Comment by kyakovenko** [comment]
Hello xDrFred,

I've just made several fixed of problems mentioned by you.

About the other questions:

> When I try to add a pdb symbol file to the symbols "The file contains invalid data" gets displayed as soon as I click save

Could you send us an example of such file that we can test it on our side?

> I still get an exception when I try to save an empty crash but it's working now when a dmp File is uploaded. Furthermore when I try to upload a crash report which would exeed the file system size I get an exception. (Maybe display a message in the ui?)

As I know we have a limit of a client max body size which is 2048m. So if you use S3 to store files, 30-40 Gb disk should be enough to process requests except cases when malefactors specially try to kill your system. However, in this case you can just decrease a size of max body size in nginx config file.

By the way, I would recommend you to look at our monitoring system and rules of auto deletions which you can set, it might help you.

**Comment by xDrFred** [comment]
First of all thank you very much for your effort! I'm just testing it and everything looks perfect.

> Could you send us an example of such file that we can test it on our side?

I can reproduce it with the following file. It's from a .NET C# Application. I just stumbled over this but we will most likely not use this feature as we will dump our symbols to another symbol server. (Or do I misunderstand this feature)
[Omaha.Exception.zip](https://github.com/Crystalnix/omaha-server/files/383722/Omaha.Exception.zip)

And I'll just change the auto deletion rulles as you suggested.

**Comment by kyakovenko** [comment]
I figured out what is the problem. The point is that at the moment we don't support uploading any symbol files except special Breakpad symbol files. You can read about this format more [here](https://chromium.googlesource.com/breakpad/breakpad/+/master/docs/processor_design.md#Symbol-Files) and [here](https://chromium.googlesource.com/breakpad/breakpad/+/master/docs/symbol_files.md).

Actually, we have plans to implement a support of pdb symbol files. There is a special ticket for this. (#25) but I can't say exactly when it'll be done.

By the way, what another symbol server are you going to use?

**Comment by xDrFred** [comment]
Probably just a file storage or a solution like this ([nuget symbol server](http://www.xavierdecoster.com/setting-up-your-own-symbolsource-server-step-by-step))

As the symbols aren't delivered to the customers and as we do not need a symbolserver open to the public we will most likely host it internal seperated from the omaha-server. Also to reduce disk usage on the external hosting.
