### ISSUE TITLE
Bad Request 400

### ISSUE THREAD

**Issue by synapsy88** [Crystalnix/omaha-server#223]
HI, 

why server return status code 400 Bad Request ? 

The appid is the same server and client launch application 

launch this instruction 

TradeUpdate.exe /install "bundlename=Shop&appguid={EB3205B9-3DA8-4229-B4B6-40B8547829DA}&appname=Shop&needsadmin=True&lang=it"

this is log 
http://pastebin.com/N5QVrU5D
`

**Comment by kyakovenko** [comment]
Hello @synapsy88,

It seems that something is wrong with your CUP settings because other requests were processed well.
Have you set CUP_PEM_KEYS parameter?

**Comment by synapsy88** [comment]
Hi @kyakovenko,

Yes , finally I fix my problem myself. 

Thanks you for support
