### ISSUE TITLE
Can not get omaha-server to work with docker-compose

### ISSUE THREAD

**Issue by xakraz** [Crystalnix/omaha-server#233]
Hello,

I am really interested by your omaha-server but I can not manage to get a running instance with docker-compose.

```
$ docker-compose --file docker-compose.dev.yml up web
omahaserver_db_1 is up-to-date
Creating omahaserver_redis_1
Creating omahaserver_web_1
Attaching to omahaserver_web_1
web_1    | Raven is not configured (logging is disabled). Please see the documentation for more information.
web_1    | ---> pavement.docker_run
web_1    | ---> pavement.migrate
web_1    | ./manage.py migrate --noinput
web_1    | Traceback (most recent call last):
web_1    |   File "./manage.py", line 11, in <module>
web_1    |     execute_from_command_line(sys.argv)
web_1    |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
web_1    |     utility.execute()
web_1    |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 303, in execute
web_1    |     settings.INSTALLED_APPS
web_1    |   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 48, in __getattr__
web_1    |     self._setup(name)
web_1    |   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 44, in _setup
web_1    |     self._wrapped = Settings(settings_module)
web_1    |   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 92, in __init__
web_1    |     mod = importlib.import_module(self.SETTINGS_MODULE)
web_1    |   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
web_1    |     __import__(name)
web_1    |   File "/srv/omaha/omaha_server/omaha_server/settings.py", line 48, in <module>
web_1    |     'absolute.context_processors.absolute',
web_1    | TypeError: can only concatenate tuple (not "list") to tuple
web_1    |
web_1    |
web_1    | Captured Task Output:
web_1    | ---------------------
web_1    |
web_1    | ---> pavement.docker_run
web_1    | ---> pavement.migrate
web_1    | ./manage.py migrate --noinput
web_1    |
web_1    | Build failed running pavement.docker_run: Subprocess return code: 1
omahaserver_web_1 exited with code 1
```

I have tried the dev branch and the tag 0.4.2 without any luck.
Am I missing something ?

Sorry for such a noob question :D

**Comment by kyakovenko** [comment]
Hello Xavier,

Thank you for contacting us. We'll look at this problem during next 2 weeks.
While we're working on this issue, you can use compiled docker images through the `docker pull` command. Our docker hub link is https://hub.docker.com/r/crystalnix/omaha-server/

Best regards,
Kirill

**Comment by xakraz** [comment]
Hello @kyakovenko,

Thanks for your quick answer.
Is there some kind of a documentation were it explains how to run your image ?
Should the `docker-compose.yml` file just work ?

**Comment by kyakovenko** [comment]
Hello @xakraz,

Unfortunately, there is no a documentation in our repository explaining how to launch a docker image in a container.

There are two common ways:

1. You can run out image using the `docker run` command-line with a specific environment variables. More information you can find here: https://docs.docker.com/engine/reference/run/#/env-environment-variables
1. You can use `docker-compose up` command-line. In this case it should use the `docker-compose.yml` file and pull all required images from Docker Hub.

**Comment by xakraz** [comment]
Hello @kyakovenko ,

Thanks for your help.
By the way, I think that the tag `stable` is not up-to-date to the latest tag of your code...

Have you any example or tips for a CoreOS update management usage ?

**Comment by anmekin** [comment]
Hello @xakraz,

Unfortunately, we don't have any example for CoreOS because we don't use it.
