### ISSUE TITLE
How to support update and fresh Install at the same time

### ISSUE THREAD

**Issue by Bivek** [Crystalnix/omaha-server#241]
I am using omaha crystalnix server and google omaha client for an auto update/installation of one of our software. The problem I am facing right now is when a new version of software is available and I upload it with an `update` action, it works for those users for which the software is already installed and not for the fresh installer. However, if the action is changed to `install` it works for the fresh installer but software would not be auto updated for the one who is already using the older version.
I also tried with having both `install` and `update` actions  but it is still not working.

What is the right way to support both?

**Comment by Bivek** [comment]
@shashkin it seems you guys are able to manage it. Would you not mind helping me out

**Comment by shashkin** [comment]
Hi @Bivek 
Unfortunately I do not work on this project anymore, but I'm sure the guys will help you.

**Comment by kyakovenko** [comment]
Hello @Bivek,

It's correct behaviour and if you want to launch the same action for existing and new users, you should create two actions.
