### ISSUE TITLE
Server responding NoneNone domain

### ISSUE THREAD

**Issue by SulfredLee** [Crystalnix/omaha-server#264]
I am using Ubuntu 14.04 LTS 64bit.
I downloaded omaha-server and run with Docker.

I build an omaha-client by myself, then I follow [this tutorial](https://fman.io/blog/google-omaha-tutorial/) to try to install application through omaha client and server, I am able to upload the install.exe to the server. I then run the Updater.exe under debug mode. From the debug logger, I found:
```
<response protocol="3.0" server="prod">
  <daystart elapsed_seconds="21832" elapsed_days="3809"/>
  <app status="ok" appid="{B315AE28-39AD-4367-802B-9A940EE4D54B}">
    <updatecheck status="ok">
      <urls>
        <url codebase="None://NoneNone/static/media/build/TestApp/stable/win/65536/"/>
      </urls>
      <manifest version="0.0.1.0">
        <packages>
          <package required="true" hash="Z3ExpaqpQvHJ1n3W/u68+1Gi8AU=" name="install.exe" size="1183232"/>
        </packages>
      </manifest>
    </updatecheck>
  </app>
</response>
```

Which is a response sent from server, I am afraid this is no an error but is that I didn't config the server in a correct way. Could anyone provide some guideline for the server setting?

If this is not a place to ask question, any other places I can use to discuss this server?

**Comment by anmekin** [comment]
Hi SulfredLee,
You need to set up the OMAHA_URL_PREFIX environment variable. For example, http://localhost:9090

**Comment by SulfredLee** [comment]
Thank you very much.

2017-06-14 19:10 GMT+08:00 Andrey Mekin <notifications@github.com>:
