### ISSUE TITLE
How to use CUP encryption

### ISSUE THREAD

**Issue by SulfredLee** [Crystalnix/omaha-server#267]
I followed the steps at the bottom of the readme file.

1. Use Omaha eckeytool ...
2. Add cup_ecdsa_pubkey.{KEYID}.h to...
3. Add private.pem keyid ...

I have something like this in settings.py file
`CUP_PEM_KEYS = {
    # 'keyid': 'private_key_path',
    1: /absolute/path/to/privatekey,
}`

I have the file `priv.pem` inside `/absolute/path/to/privatekey`

Then I start the server by `sudo paver up_local_dev_server`.
I use firefox to request the server, `http://127.0.0.1:9090/admin`. Firefox report `Unable to connect`, it seems the server cannot start.

One more question, how can I print log from the server?

**Comment by kyakovenko** [comment]
Hello @SulfredLee,

I see it's been a long time. Do you still have this problem?

**Comment by SulfredLee** [comment]
Hello,

No it is not. Thank you very much.

2017-09-14 18:50 GMT+08:00 Kirill Yakovenko <notifications@github.com>:
