### ISSUE TITLE
Latest Google Omaha client fails to install

### ISSUE THREAD

**Issue by asesh** [Crystalnix/omaha-server#268]
I have just merged m33: https://github.com/google/omaha/tree/m33 branch from Google Omaha client and after doing so, updating fails. After going through the log, looks like Google have added sending more data to the server which Omaha server doesn't support right now. Can you guys replicate this issue from your side too? 

Thanks

**Comment by asesh** [comment]
@anmekin can you please answer this question? I can provide the logs if you need them. Thanks

**Comment by anmekin** [comment]
Hi @asesh,
Yes, the logs will be very useful.

**Comment by asesh** [comment]
Thanks for replying. I have fixed the issue. It was because of merged public key from upstream so I replaced those keys with ours and it's working again. Thanks
