### ISSUE TITLE
Crash reports from Chromium 59 won't upload

### ISSUE THREAD

**Issue by asesh** [Crystalnix/omaha-server#271]
Hello, have you guys noticed that Crash reports from Chromium 59 won't upload on this version of Omaha server but however crash reports from Chromium 57 still works. Are you guys aware of this issue and do you have any idea on why it's not working? @anmekin

**Comment by asesh** [comment]
if you don't want to make changes to the server then here's how to fix this issue: https://groups.google.com/a/chromium.org/forum/#!topic/chromium-dev/VugOJeSsPV4

**Comment by kyakovenko** [comment]
Hello @asesh,

Thank you for letting us know. We've disabled gzipping for now but we're planning to fix this issue in the near future.

**Comment by asesh** [comment]
@kyakovenko Thanks

**Comment by asesh** [comment]
I think this issue should remain open until and unless there's a fix for it. So I am reopening it again.

**Comment by kyakovenko** [comment]
Hello @asesh,

We've added support of gzipped crashes. Could you take a look?

**Comment by asesh** [comment]
@kyakovenko Thanks for fixing this issue but we have no plan to add these changes any time soon cause we are using that workaround right now. If it's been fixed then please close this issue. Thanks again
