### ISSUE TITLE
Deploying Omaha-Server to AWS Elastic Beanstalk

### ISSUE THREAD

**Issue by marcelodevi** [Crystalnix/omaha-server#310]
I'm having a problem uploading the project to AWS, I followed the steps of the link https://github.com/Crystalnix/omaha-server/wiki/Guide-to-deploying-and-installing-omaha-server-in-production
The project goes up to AWS normally, but after a while the health of the application gets RED.

I've made several unsuccessful attempts. Could someone please help me?

settings.yml
![capturar copia](https://user-images.githubusercontent.com/24438281/35652607-710b103a-06cb-11e8-9a4a-7b9d661dfc1e.png)

-------------------------------------
/var/log/docker
-------------------------------------
\nWed Jan 31 21:46:07 UTC 2018\n
time="2018-01-31T21:46:08.157041888Z" level=info msg="libcontainerd: new containerd process, pid: 2636" 
time="2018-01-31T21:46:09.174894275Z" level=warning msg="failed to rename /var/lib/docker/tmp for background deletion: rename /var/lib/docker/tmp /var/lib/docker/tmp-old: no such file or directory. Deleting synchronously" 
time="2018-01-31T21:46:09.234511261Z" level=info msg="Graph migration to content-addressability took 0.00 seconds" 
time="2018-01-31T21:46:09.234718657Z" level=warning msg="Your kernel does not support cgroup blkio weight" 
time="2018-01-31T21:46:09.234734689Z" level=warning msg="Your kernel does not support cgroup blkio weight_device" 
time="2018-01-31T21:46:09.234811196Z" level=warning msg="mountpoint for pids not found" 
time="2018-01-31T21:46:09.235007574Z" level=info msg="Loading containers: start." 
time="2018-01-31T21:46:09.534681514Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address" 
time="2018-01-31T21:46:09.702040783Z" level=info msg="Loading containers: done." 
time="2018-01-31T21:46:09.772973031Z" level=info msg="Docker daemon" commit="402dd4a/17.09.1-ce" graphdriver(s)=overlay2 version=17.09.1-ce 
time="2018-01-31T21:46:09.773511108Z" level=info msg="Daemon has completed initialization" 
time="2018-01-31T21:46:09.785344080Z" level=info msg="API listen on /var/run/docker.sock" 
time="2018-01-31T21:46:14.868890647Z" level=info msg="Processing signal 'terminated'" 
time="2018-01-31T21:46:14.869818063Z" level=info msg="stopping containerd after receiving terminated" 
\nWed Jan 31 21:46:16 UTC 2018\n
time="2018-01-31T21:46:16.661839183Z" level=info msg="libcontainerd: new containerd process, pid: 3343" 
time="2018-01-31T21:46:17.673469198Z" level=warning msg="failed to rename /var/lib/docker/tmp for background deletion: rename /var/lib/docker/tmp /var/lib/docker/tmp-old: no such file or directory. Deleting synchronously" 
time="2018-01-31T21:46:17.709520634Z" level=info msg="devmapper: Creating filesystem ext4 on device docker-202:1-399863-base" 
time="2018-01-31T21:46:45.921355147Z" level=info msg="devmapper: Successfully created filesystem ext4 on device docker-202:1-399863-base" 
time="2018-01-31T21:46:45.952302265Z" level=info msg="Graph migration to content-addressability took 0.00 seconds" 
time="2018-01-31T21:46:45.952471542Z" level=warning msg="Your kernel does not support cgroup blkio weight" 
time="2018-01-31T21:46:45.952487382Z" level=warning msg="Your kernel does not support cgroup blkio weight_device" 
time="2018-01-31T21:46:45.952579661Z" level=warning msg="mountpoint for pids not found" 
time="2018-01-31T21:46:45.953214048Z" level=info msg="Loading containers: start." 
time="2018-01-31T21:46:46.031506740Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address" 
time="2018-01-31T21:46:46.057712427Z" level=info msg="Loading containers: done." 
time="2018-01-31T21:46:46.097845756Z" level=info msg="Docker daemon" commit="402dd4a/17.09.1-ce" graphdriver(s)=devicemapper version=17.09.1-ce 
time="2018-01-31T21:46:46.097973439Z" level=info msg="Daemon has completed initialization" 
time="2018-01-31T21:46:46.110277661Z" level=info msg="API listen on /var/run/docker.sock" 
time="2018-01-31T21:47:28.757339284Z" level=info msg="Layer sha256:60f4047e422e4971d85c1216909d59baa37807ec8efe4ed047162ee948dd2b4c cleaned up" 
time="2018-01-31T21:47:31.778137708Z" level=info msg="Layer sha256:60f4047e422e4971d85c1216909d59baa37807ec8efe4ed047162ee948dd2b4c cleaned up" 
time="2018-01-31T22:07:07.428651116Z" level=info msg="Layer sha256:7fd5aed47566633bd162e2e8a8d840235775690d92ef5d692059b2b24fb88ee2 cleaned up" 
time="2018-01-31T22:07:25.563301698Z" level=info msg="Container 68692a615353cfd3eaea5aa0f6762e94c52176dd78dd4f0843f086f5e6d3d2ab failed to exit within 10 seconds of signal 15 - using the force" 
time="2018-01-31T22:13:57.744238420Z" level=info msg="Container 003065325a0aa8553db2da5fc3abeb2be52f9a4bf1e965d0c6eb4b84ca0f7ac6 failed to exit within 10 seconds of signal 15 - using the force" 
time="2018-01-31T22:15:04.289920718Z" level=info msg="Container 0d4b1bf4a2872d7c073a914655afd002f80cdd14199f55d994849956d7db386d failed to exit within 10 seconds of signal 15 - using the force" 

-------------------------------------
/var/log/eb-docker/containers/eb-current-app/3b3317275d57-stdouterr.log
-------------------------------------
---> pavement.docker_run
/usr/bin/supervisord
/usr/lib/python2.7/dist-packages/supervisor/options.py:295: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
2018-01-31 22:14:48,401 CRIT Supervisor running as root (no user in config file)
2018-01-31 22:14:48,402 WARN Included extra file "/etc/supervisor/conf.d/supervisord.conf" during parsing
2018-01-31 22:14:48,424 INFO RPC interface 'supervisor' initialized
2018-01-31 22:14:48,424 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2018-01-31 22:14:48,424 INFO supervisord started with pid 8
2018-01-31 22:14:49,427 INFO spawned: 'celery' with pid 11
2018-01-31 22:14:49,429 INFO spawned: 'nginx-app' with pid 12
2018-01-31 22:14:49,431 INFO spawned: 'omaha' with pid 13
2018-01-31 22:14:49,432 INFO spawned: 's3fs' with pid 14
2018-01-31 22:14:49,658 INFO exited: s3fs (exit status 1; not expected)
2018-01-31 22:14:50,660 INFO success: nginx-app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-01-31 22:14:50,660 INFO success: omaha entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-01-31 22:14:50,661 INFO spawned: 's3fs' with pid 31
2018-01-31 22:14:50,685 INFO exited: s3fs (exit status 1; not expected)
2018-01-31 22:14:53,028 INFO spawned: 's3fs' with pid 114
2018-01-31 22:14:53,038 INFO exited: s3fs (exit status 1; not expected)
2018-01-31 22:14:56,819 INFO spawned: 's3fs' with pid 115
2018-01-31 22:14:56,826 INFO exited: s3fs (exit status 1; not expected)
2018-01-31 22:14:57,827 INFO gave up: s3fs entered FATAL state, too many start retries too quickly
2018-01-31 22:14:59,829 INFO success: celery entered RUNNING state, process has stayed up for > than 10 seconds (startsecs)

**Comment by kajisaap** [comment]
In the same boat. Many of the artifacts for `AWS Elastic Beanstalk` in wikis, eb configurations and tweaks are terribly outdated. Let me know if you have many any progress - keenly interested to learn more.

**Comment by kyakovenko** [comment]
@marcelodevi thanks to the feedback.
