### ISSUE TITLE
Crash dumps are publicly readable for every AWS users

### ISSUE THREAD

**Issue by q71114** [Crystalnix/omaha-server#321]
Can the read access for `Any AWS user`  be removed from the crash dumps and debug symbols that are uploaded to server? It doesn't seem right to me that anyone can access these potentially private informations. Thanks.

![image](https://user-images.githubusercontent.com/8770144/41341592-60f9daae-6efa-11e8-8772-b7876f7458e4.png)

**Comment by q71114** [comment]
We fixed it by changed [this setting](https://github.com/Crystalnix/omaha-server/blob/master/omaha_server/omaha_server/settings_prod.py#L29) to `private`

**Comment by RyanJarv** [comment]
@q71114 do you mind opening this back up? I can't imagine this is is on purpose.

I suspect it's due to misunderstanding the `authenticated_read` ACL which allows *any* authenticated user to access the content.

https://github.com/Crystalnix/omaha-server/issues/321

**Comment by anmekin** [comment]
Thanks for the issue and PR.
