### ISSUE TITLE
No statistics because no userid is sent with update client

### ISSUE THREAD

**Issue by q71114** [Crystalnix/omaha-server#322]
It's not an issue, but a question. 
I noticed that statistics are only generated when the client is sending `userid` with the update events, but our Omaha client doesn't send `userid` with any requests. (We could only simulate it by creating the `uid` registry key manually) How do we force the client to create the `userid` and send it along with the update events?

**Comment by q71114** [comment]
I turned it on with`usagestats=1` tag.

**Comment by fydeos-alpha** [comment]
@q71114 same issue here, where did you turn `usagestats=1`, mind elaborate please? thanks.

**Comment by q71114** [comment]
You just need to add `usagestats=1` to the parameters. 
For example when creating a web installer with `ApplyTag.exe`:
```
ApplyTag.exe GoogleUpdateSetup.exe output.exe "appguid=<appId>&appname=<appName>&needsadmin=True&usagestats=1"
```
When calling an offline installer package:
```
GoogleUpdate.exe /installsource taggedmi /install "appguid=<appId>&appname=<appName>&needsadmin=True&lang=en&usagestats=1"
```
