### ISSUE TITLE
Regenerate stack trace for existing crash report

### ISSUE THREAD

**Issue by shashkin** [Crystalnix/omaha-server#34]
It can be useful in cases where we receive crash report but can not extract full stack trace because of missing symbol files.

In this case we upload all missing symbol files, then go to crash detail in admin panel and trigger stack trace generating manually.

**Comment by yurtaev** [comment]
![screenshot 2015-02-24 15 28 50](https://cloud.githubusercontent.com/assets/444503/6347133/4f88d12c-bc37-11e4-900f-f2e09ea1a5e5.png)

11b86ec258e331ed39fecab7c51a225ccfbae69e
