### ISSUE TITLE
Must we open source the fork of Omaha server?

### ISSUE THREAD

**Issue by asesh** [Crystalnix/omaha-server#350]
I just went through the license under which Omaha server's source code is distributed but I didn't find the answer to it. Suppose I create a fork of Omaha server then can I keep that fork's source code private but still use the modified fork? 

Thanks

**Comment by kyakovenko** [comment]
Hey @asesh, the Apache License 2.0 allows private use and modification but you still have to keep the license and copyright notices, and list changes done by you.

**Comment by asesh** [comment]
@kyakovenko What about the source code? Can we still keep the modified source code private? What about the list of changes? Should the list of changes be kept private to us or should it be visible to public? Thanks

**Comment by kyakovenko** [comment]
The license doesn't say anything about private storing of the source code, so I consider it as not forbidden, but you must state your changes and refer to the original authorship, especially, when you use it for commercial purposes.

**Comment by asesh** [comment]
Thanks a lot :)
