### ISSUE TITLE
How to use "Actions" and "Partial updates" in "Home » Omaha » Versions » Add version"

### ISSUE THREAD

**Issue by quyen194** [Crystalnix/omaha-server#38]
![omaha_server_addversion](https://cloud.githubusercontent.com/assets/10302404/6163731/96c2d9c0-b2c8-11e4-9527-529765491982.png)
I plan to make an patch update (small size download) with courgette in chromium, and i think above module is created for that (or am i wrong?) but don't know how to use it
Could you please do me some suggesstions! Thanks

**Comment by shashkin** [comment]
Actions are described here https://code.google.com/p/omaha/wiki/ServerProtocol#actions_Element
Partial updates are updates that will not be applied to all users but to some % of them.

**Comment by quyen194** [comment]
Omg my bad, thank you in advance
So do you know how to make small update with your omaha server or i need to do it in chromium side?
