### ISSUE TITLE
Why server always responds the highest version

### ISSUE THREAD

**Issue by quyen194** [Crystalnix/omaha-server#42]
Hi, thanks for your time,
My Chromium release has 2 versions:
mini_installer_31_0_1650_57.exe => full installers with 26mb size
mini_installer_31_0_1650_58.exe => patch update with 17 kb size
They need to be installed one by one in order 57 then 58 (I can install offline successfully)
When I upload them to omaha server, I run tagged GoogleUpdateSetup.exe created from:
ApplyTag.exe GoogleUpdateSetup.exe BChromeSetup.exe "appguid={4994F468-38FE-4D21-B659-A77C659E4A9A}&appname=BChrome&needsadmin=False&lang=en&usagestats=1&channel=dev"
It always download the version 58 => so alway failed because 58 need 57 already installed
So what's wrong?
Thanks for help,

**Comment by shashkin** [comment]
> Why server always responds the highest version?

What kind of response (according to server protocol specs) are you expecting in your case?

**Comment by quyen194** [comment]
I expect it response 57 for full installation then next request (after 57 is installed) server respond 58 for update
I try choose "install" "update" "postinstall" "preinstall" but nothing new happend :(

**Comment by shashkin** [comment]
At this moment our server does not support partial updates with Omaha and we have no plans to add this feature in the near future.

If you need this feature, I can suggest you to implement it by yourself and then submit it as patch or pull request so we can review it and push it in.

**Comment by quyen194** [comment]
Thank you very much. I would try then if success I will submit it :D
