### ISSUE TITLE
Upgrade django 1.7 to 1.8

### ISSUE THREAD

**Issue by yurtaev** [Crystalnix/omaha-server#43]
- [x] Django debug toolbar issue [#668](https://github.com/django-debug-toolbar/django-debug-toolbar/issues/668)
- [x] django-nose issue [#178](https://github.com/django-nose/django-nose/issues/178)
- [x] [Upgrading templates to Django 1.8](Upgrading templates to Django 1.8)
- [x] [django.conf.urls.patterns](https://docs.djangoproject.com/en/dev/releases/1.8/#django-conf-urls-patterns)
- [x] [django-httplog](https://github.com/futurecolors/django-httplog)
- [x] [django-redis 4.0](https://github.com/niwibe/django-redis)

**Comment by quyen194** [comment]
which ide you use to work with this project? I'm using window 7. I wanna implement the partial update my self.
and another question: i update the code with "git pull ..." but after that i can't up server again with "sudo paver up_local_dev_server". May i have to rebuild project? and how to do that?
Thank you very much!

**Comment by quyen194** [comment]
and newest source give me that error:
AttributeError at /admin/

'module' object has no attribute 'DictField'

Request Method: 	GET
Request URL: 	http://103.XXX.XXX.XXX:9090/admin/
Django Version: 	1.7.3
Exception Type: 	AttributeError
Exception Value: 	

'module' object has no attribute 'DictField'

Exception Location: 	./omaha/serializers.py in StatisticsMonthsSerializer, line 77
Python Executable: 	/usr/bin/uwsgi-core
Python Version: 	2.7.6
Python Path: 	

['.',
 '',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/srv/omaha/omaha_server']

Server time: 	Fri, 27 Feb 2015 10:26:04 +0000

**Comment by yurtaev** [comment]
I use OS X & PyCharm.

Try run fig command:

```shell
$ fig -f fig-dev.yml up web
```
and

```shell
$ fig rm db
$ fig rm web
$ fig build db
$ fig build web
$ paver up_local_dev_server
```

it should help

**Comment by quyen194** [comment]
Thanks

**Comment by ALAINAbbe** [comment]
A lot of comments here https://github.com/django-nose/django-nose/issues/178 would love to see this done soon +1
