### ISSUE TITLE
How to change update respond from "latest version" to "next version"?

### ISSUE THREAD

**Issue by quyen194** [Crystalnix/omaha-server#44]
I saw code in file: omaha-server\omaha_server\omaha\builder.py
line 98-100:
        qs = qs.filter(Q(partialupdate__isnull=True)
                       | Q(partialupdate__is_enabled=False))
        new_version = qs.cache().latest('version')

I can't find what "qs" is and its class :( do I find right place to change? or it's related in another place?
Thanks,

**Comment by yurtaev** [comment]
`qs` is django [QuerySet](https://docs.djangoproject.com/en/1.7/ref/models/querysets/). You can change the query to meet your needs
