### ISSUE TITLE
Duplicate Symbol files can be uploaded

### ISSUE THREAD

**Issue by debinzhang** [Crystalnix/omaha-server#45]
Viasat automation team is testing symbol upload functionality. They found duplicate symbol files (with same debug ID) can be uploaded to server. For example, on the server there are two uploads with the same ID: 6233AAF7BA5D4AF1B4C4BD8114DBD10E6. They do not think we should allow duplicate entries.  They should either overwrite the existing entry and file, or we should cancel the upload and send back a 400 HTTP response

**Comment by shashkin** [comment]
I think the pair "Debug filename and Debug ID" should be unique

**Comment by yurtaev** [comment]
What is the current status of the issue?
