### ISSUE TITLE
Omaha client not downloading mini-installer from correct omaha server

### ISSUE THREAD

**Issue by chadgoss** [Crystalnix/omaha-server#61]
- create two omaha servers

To reproduce, from the same PC:
- use metainstaller pointed at first omaha server to download browser miniinstaller from first omaha server
- uninstall browser
- use metainstaller pointed at second omaha server to download miniinstaller from second. The metainstaller will not go to the second omaha-server, it will download from the first.

**Comment by quyen194** [comment]
check const_addresses.h of both miniinstaller for sure

**Comment by shashkin** [comment]
Moved to https://github.com/Crystalnix/omaha/issues/24 as this is related to Omaha client
