### ISSUE TITLE
Add REST API for viewing crash reports

### ISSUE THREAD

**Issue by shashkin** [Crystalnix/omaha-server#65]
@cogren1 wrote:

> The REST API needs the ability to poll the Omaha server for JSON of all crash reports and also the ability to poll the Omaha server for JSON of a specific crash report as specified by the crash report's ID.

(moved from https://github.com/Crystalnix/omaha/issues/23)

**Comment by yurtaev** [comment]
@cogren1 http://crystalnix.github.io/omaha-server/#page:crash-reports
