### ISSUE TITLE
How to setup Https without install EWS BeanStalk

### ISSUE THREAD

**Issue by namtb49** [Crystalnix/omaha-server#71]
In my own application, I've search for some common approach to support auto update feature. At the moment I found that Omaha  protocol is good one and CrystalIngix is famous open-source server has support that .
But I've faced up with a problem before decided to implement in my project. Suppose that, in my near future plan, I want to install some client-server certificate, i.e https connection to setup the secure tunnel between client and update server, how would I do that in CrystalIngix without mess up with third party EWS Beanstalk, as described in manual page ? (Because in experiment process, I want to test it in some free webserver, it's really difficult to install some cloud webservie belong to Amazon)

Thanks for your patience

**Comment by yurtaev** [comment]
Self-Hosted Solution:

- Ubuntu Trusty 14.04 (LTS) (64-bit)
- [docker](docker.com) or [boot2docker](https://github.com/boot2docker/boot2docker) for OS X & Windows
- [docker-compose](https://docs.docker.com/compose/install/)

```sh
# To change Omaha-Server configuration, add the settings that you want to modify to the `docker-compose.yml` file (SECRET_KEY, AWS_ACCESS_KEY_ID and etc)
$ sudo docker-compose up -d
# this server is running on port 9090
# configure NGINX (with ssl) as a reverse proxy for omaha server
# nginx 80/443 port <----> omaha-server 9090 port
```

**Comment by namtb49** [comment]
Thanks in advance. In early morning, I setup successful my web server with Crystalnix, and I connect properly with my application.
Sorry for my ignorance, but after change docker's configure file as you show in prev post, how do I register pfx/cert key to my server ?

**Comment by yurtaev** [comment]
1. Buy SSL Certificates
    - https://www.gandi.net/ssl
    - https://www.rapidssl.com/buy-ssl/
2. Configure Nginx to Use SSL
    - https://www.digitalocean.com/community/tutorials/how-to-create-an-ssl-certificate-on-nginx-for-ubuntu-14-04

**Comment by AMartens181** [comment]
If you wanted to deploy to Azure, how would you do that?

**Comment by kyakovenko** [comment]
Hello @AMartens181,

We would create a separate docker image as we have done for Amazon and GCP. I think the main issue will relate to storage settings. You will possibly have to set up some additional libraries for Azure Blob Storage.

At the moment, Omaha-Server doesn't officially support Azure. However, if you need some help with deploying Omaha-Server to Azure, you can use our contact form on the https://www.crystalnix.com/contact page, and our sales manager will get in touch with you.
