### ISSUE TITLE
Build omaha server error

### ISSUE THREAD

**Issue by quyen194** [Crystalnix/omaha-server#72]
I use below commands
$ sudo apt-get update
$ sudo apt-get install docker.io
$ sudo apt-get install python-paver python-pip
$ sudo pip install -U docker-compose
$ git clone https://github.com/Crystalnix/omaha-server.git
$ cd omaha-server
$ sudo paver up_local_dev_server

but with last command: sudo paver up_local_dev_server
I get that error:

ubuntu@bchrome:~/omaha_server/version0001/omaha-server$ sudo paver up_local_dev_server
---> pavement.up_local_dev_server
docker-compose -f docker-compose.dev.yml -p dev up -d db
Couldn't connect to Docker daemon at http+unix://var/run/docker.sock - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

Captured Task Output:
---------------------

---> pavement.up_local_dev_server
docker-compose -f docker-compose.dev.yml -p dev up -d db

Build failed running pavement.up_local_dev_server: Subprocess return code: 1

**Comment by yurtaev** [comment]
Try running `sudo service docker restart` on the server, then check /var/log/upstart/docker.log to see if Docker is throwing any errors.

**Comment by quyen194** [comment]
I Found this in log @@
/var/run/docker.sock is up
^[[31mFATA^[[0m[0000] Error starting daemon: error initializing graphdriver: "/var/lib/docker" contains other graphdrivers: devicemapper; Please cleanup or explicitly choose storage driver (-s <DRIVER>)

**Comment by quyen194** [comment]
it good now
SOLVED:
I have to add 1 line to /etc/default/docker
DOCKER_OPTS="--storage-driver=devicemapper"
