### ISSUE TITLE
About Partial Update feature

### ISSUE THREAD

**Issue by namtb49** [Crystalnix/omaha-server#73]
Thank CrystalIngyx's author for fully support my app and also answers for all silly question.
I've try apply your open-source server and it's worked well. Now I continue to discover some CystalIngyx's feature  to suited my app desire.
 
Following "Add new version"'s manual page,  I'm wondering about setup "Partial block" in add new version process. Some content in this block is so complicated such as percent, start date, end date,...
Whether this content is provisoned for scheduled purpose for some type of customer, i.e, in my knowledge, if in my development process, e.g I released version 1.0 -> 1.1 -> 1.2, etc for my customer in week 1, and if new customer start installed my app in week 2, could I combined new update to a single file, and upload this version, tinkger some info and send new update content to new customer, and formal customer have not bad effect ? 

Pls, give me some detail about this block of content. Do Crystalnix support more complex update scenario than simple download and install new version ?

**Comment by shashkin** [comment]
The "Partial Update" block allows you to push the new version to the limited amount of your users.
The "Percent" fields defines which percent of your "active" users will receive the version update.
The "Start/End date" defined the time interval when the version will be available.
"Exclude new users": whether the new users (who performs install, not update) should be able to install this version.
"Active users": defines which users will be considered as "active" (those who shows any activity in the past week/past month/any time)

To be able to use Partial update feature you need to be sure your users have userids.

**Comment by namtb49** [comment]
Thanks for your quick response, to shed up some light in my problem
Btw, I have some problem about this question.
1. how to I define "percent" of user will be get new update with other, or using customer id to distinct customer group and after that set in in admin page.
2. If i can setup my update for limit user current using my app, may be setup one update to only customer has install app in spectific time (for e.g: week 2 -> week 3).
3. And as my prev question, can I combine many sequential update part to single one, to update smoothly for each new customer and formal customer, i.e, after install this partial update, user has most recent app ?
4. (Sorry for inconvenient). Maybe in your open source has user management feature, to control such as info in this block.

**Comment by shashkin** [comment]
1. You can not define, who exactly will receive the partial update. You only can define a percent (say, 20% of your users) and the server will automatically decide who will receive the update and who will not based on userid parameter.
2. Partial updates can not be enabled only for the users who installed your application at some specific time. It distinguishes users only by their userids.
3. I'm not sure I understand what do you mean by "combine many sequential update part to single one". This server does not support delta updates yet so all your versions must be the full application versions. If you relese 1.0 -> 1.1 -> 1.2 and some of your user will still have 1.0, 1.1 will be skipped for him and he will be updated directly to 1.2.
4. What user management feature are you talking about? What info you'd like to control?

**Comment by namtb49** [comment]
Thanks Shashkin for your patience. I will try to describe my problem more clearly again (srr with my poorly English lingo) 
In my application, each release has a small patch file(gen by other open-source tool). It can be assumed that a diff image between next release version and current version, and it's will be host in update server such as update version. After client download new patch file, it weill be recombine with current setup file to make new complete program. 

So if one customer has rely on version 1.0, and the newest version is 1.6, and still some small update patch between that is 1.1; 1.2 to 1.5. To fully update to newest version, he/she must be download and update in sequence all version between.
So I'm desired to gen one spectific version immediate between ver 1.0 and ver 1.6 to replace for all needed patch, to help my customer update to newest software without go through sluggish process, such as restart computer, download and update program. And i post it in my server and notify/ schedule/ for spectific target of my customer (based on some user info). It;s will be marvelous.

And one more question :D, As mention in your github source, I saw that bitpop Browser is some succesful update control system based on Chromium project. And that almost main purpose I need to implement in my program. May be I wrong, I think that they apply some approach to get such that feature to their client.

**Comment by shashkin** [comment]
We don't have support for diff updates yet.
Partial updates is completely different feature. "Partial" in this case means "updates to some part of users".

In current implementation, you have to upload full application installer for each version, not the small patch file.

Maybe we will add support of diff/delta updates later (see #74)
Or you can do it by yourself, pull requests are always welcome :)
