### ISSUE TITLE
Differentiate between duplicate and server error.

### ISSUE THREAD

**Issue by cogren1** [Crystalnix/omaha-server#76]
We think there is an upload issue with the Omaha server, but we are not entirely sure as we get a 500 HTTP error which could mean that there is a duplicate of the symbol or crash file on the server or something actually wrong with the server. We need a response that explicitly tells us when we try to upload a duplicate symbol or crash file.

Documenting the error codes here (http://crystalnix.github.io/omaha-server/#) would be nice, too.

**Comment by shashkin** [comment]
Got it, duplicating symbols definitely should not result into 500 error. Will fix that.

BTW, @cogren1, do you use Sentry to catch server errors? In case of 500 you can see the exact error in Sentry so you can know what exactly happened.

**Comment by anmekin** [comment]
#89
