### ISSUE TITLE
How to add new field for new filter?

### ISSUE THREAD

**Issue by quyen194** [Crystalnix/omaha-server#77]
I explore the project, see that it have filter for app_id, platform, channel, version

`omaha_server\omaha\builder.py`
I just wanna add a boolean variable for filter: is_full, it's mean the version upload is full package (big size) or update package (small size)
I try add like this:
`omaha_server\omaha\models.py`
Line 91-100:

     is_enabled = models.BooleanField(default=True)
     app = models.ForeignKey(Application)
     platform = models.ForeignKey(Platform, db_index=True)
     channel = models.ForeignKey(Channel, db_index=True)
     version = VersionField(help_text='Format: 255.255.65535.65535', number_bits=(8, 8, 16, 16), db_index=True)
     release_notes = models.TextField(blank=True, null=True)
     file = models.FileField(upload_to=_version_upload_to)
     file_hash = models.CharField(verbose_name='Hash', max_length=140, null=True, blank=True)
     file_size = models.PositiveIntegerField(null=True, blank=True)
     is_full = models.BooleanField(default=False)

`omaha_server\omaha\serializers.py`
Line 61-66:

    class Meta:
        model = Version
        fields = ('id', 'is_enabled', 'app', 'platform', 'channel',
                  'version', 'release_notes', 'file', 'file_hash', 'file_size',
                  'is_full', 'created', 'modified')
        read_only_fields = ('created', 'modified')

new file:
`omaha_server\omaha\migrations\0017_is_full_20150609_0855.py`

    # -*- coding: utf-8 -*-
    from __future__ import unicode_literals

    from django.db import models, migrations

    class Migration(migrations.Migration):

        dependencies = [
            ('omaha', '0016_auto_20150207_0911'),
        ]

        operations = [
            migrations.AddField(
                model_name='version',
                name='is_full',
                field=models.BooleanField(default=False),
                preserve_default=False,
            ),
        ]

But project build failed :(
Please tell me how to do it, Thanks so much!

**Comment by shashkin** [comment]
What do you mean by "project build failed"? Any error message or traceback? It's hard to guess what's your problem is.

BTW, could you please use better formatting in your messages next time? It's hard to read the code messed up by github's markdown.

**Comment by quyen194** [comment]
Sorry i don't know how to format, i didn't see any panel in comment.
I try to build project, it show no error, show as normal. But when i saw in project folder, some file *.py do not compiled (to *.pyc) :(
how could I send you, or upload here the files I edited?

**Comment by shashkin** [comment]
How do you "build" the project?
Is your server up and running?
Are there any server errors?

**Comment by quyen194** [comment]
My server is running for weeks, then i modify and now i can't make it up again :( just after edit, I try revert to original code, but not success :(
How to build: i delete related *.pyc file and run sudo paver up_local_dev_server again

**Comment by avli** [comment]
@quyen194 I'm afraid we'll not be able to help with the description you provided. It's not clear what the issue really is. Have you made any changes and now the server doesn't work? What errors do you see? Could you provide a stacktrace?

And about sending us patches. Basically you shouldn't do it with zip archives. Please, use [pull requests](https://help.github.com/articles/using-pull-requests/) mechanism is you want to share some patches useful for community. Thanks!

**Comment by quyen194** [comment]
sorry if i didn't make it clear,
I do not saw the stack trace when run server, it show as normal
'''
  ubuntu@bchrome-test:~/omaha-server$ sudo paver up_local_dev_server
  sudo: unable to resolve host bchrome-test
  ---> pavement.up_local_dev_server
  docker-compose -f docker-compose.dev.yml -p dev up -d db
  Recreating dev_db_1...
  docker-compose -f docker-compose.dev.yml -p dev up -d web
  Recreating dev_db_1...
  Recreating dev_redis_1...
  Recreating dev_web_1...
  Open http://{DOCKER_HOST}:9090/admin/
   username: admin
   password: admin
   ubuntu@bchrome-test:~/omaha-server$
'''
but there is no port 9090 listening and also some *.py file not compiled to *.pyc

I didn't use pull request because this not work :( i don't wanna mess it up :((

**Comment by shashkin** [comment]
@quyen194 It looks like this discussion is not really about this project but about how to work with python, django and docker in general.

I'm afraid we're not going to teach anybody how these instruments work, so you have to learn them by yourself before you'll be able to implement anything.
And we're definitely not going to implement the features if they're not needed for us.

I believe you will find the solution of your problem after you become more familiar with the technologies you're using.

Thanks and good luck.
