### ISSUE TITLE
Feature request: Rest API to add application data

### ISSUE THREAD

**Issue by chadgoss** [Crystalnix/omaha-server#97]
We can currently create omaha-->versions using the API, but we need the ability also to add data.

**Comment by anmekin** [comment]
Do you mean the ability to edit existing version?

**Comment by shashkin** [comment]
I think it's about installer data attributes which belong to Application
@chadgoss am I right?

**Comment by chadgoss** [comment]
@shashkin yes, this is about adding/editing application data attributes

**Comment by anmekin** [comment]
#100
